"""
05_lead_analyst.py
"""
import importlib
base_agent = importlib.import_module("pipeline.11_specialist_agents.base_agent")
BaseFinancialAgent = base_agent.BaseFinancialAgent

class LeadAnalyst(BaseFinancialAgent):
    def _get_task_instruction(self) -> str:
        return """You are the Lead Analyst. Your input is the text generated by the specialized agents (Financial, Business, Management, Risk).
        You must synthesize this into structured intelligence ONLY. No paragraphs.
        
        Example Output Format:
        {
          "growth": {
            "status": "positive/stable/negative",
            "confidence": 0.95,
            "evidence": ["record deal wins", "strong segment performance"]
          },
          "profitability": {
            "status": "stable/expanding/contracting",
            "confidence": 0.88,
            "evidence": ["margin expansion", "cost discipline"]
          },
          "risks": [
            "macro headwinds in Europe",
            "client concentration"
          ]
        }
        
        Return ONLY valid JSON matching this schema. Do not include markdown formatting or narrative text."""

    @staticmethod
    def generate_structured_intelligence(fa_evidence) -> dict:
        # For now, return a deterministic structured intelligence block to guide narrative writer
        return {
            "growth": {"status": "positive", "confidence": 0.90, "evidence": ["Steady revenue growth", "Pipeline expansion"]},
            "profitability": {"status": "stable", "confidence": 0.85, "evidence": ["Margin resilience", "Operating leverage"]},
            "risks": ["Macroeconomic headwinds", "Wage inflation", "Client concentration"]
        }
